
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://maex.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id to track your visitors

google-tracking-id: "UA-72326389-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Max Strübing"
title: "{ WELCOME ~ }"
description: "This is my blog, have fun here!"
keywords: "Max, Strübing, mstruebing, coder, php, javascript, linux"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: ""

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Come here they said!"
  - text: "It will be fun they said!"

me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

########
# Blog #
########

post-preview-words: 96

paginate: 10

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/sitegeist.jpeg"
    date: "August 2015 - today"
    description: "apprentice @ Sitegeist media solutions GmbH"
    link: 'https://sitegeist.de/'
  - image: "/img/timeline/gosign.jpeg"
    date: "January 2015 - March 2015"
    description: "intern @ Gosign media. GmbH"
    link: 'https://www.gosign.de/'
  - image: "/img/timeline/freiland.jpg"
    date: "September 2013 - January 2015"
    description: "dual student @ Freiland Netzlösungen GmbH"
    link: 'http://www.freiland.cc/'
  - image: "/img/timeline/fh-wedel.png"
    date: "September 2013 - April 2015"
    description: 'student @ FH-Wedel'
    link: 'http://www.fh-wedel.de/'

# First image of the Timeline

timeline-img: "/img/me.jpg"
timeline-start: "~2012"
timeline-link: 'https://www.xing.com/profile/Max_Struebing2?sc_o=mxb_p'
timeline-description: "started coding"

###########
# Contact #
###########

email: "max_struebing@gmx.de"
twitter: "https://twitter.com/mstrbng"
twitterHandle: "@mstrbng"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Max Strübing is a coder from Germany/Hamburg who loves to learn new things and likes clean code."
author_blurb_image: "/img/me.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/mstruebing"
  - title: "twitter"
    url: "https://twitter.com/mstrbng"
  - title: "xing"
    url: "https://www.xing.com/profile/Max_Struebing2?sc_o=mxb_p"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
